solutions/day06/Readme.md
solutions/day06/solution_cpp.cpp

Solution for Day 6 in C++

---

solutions/day06/solution_python.py

Implement day 6 solution using Python
Fixes # (issue)
Implemented test class within solution to validate.

feat: add day 6 python solution implementation

---

solutions/day05/solution_cpp.cpp

This pull request provides a solution to the LeetCode problem titled "Permutation in String" (Problem #567). The solution checks if one string is a permutation of another string by examining all possible substrings of the second string.
Please include a summary of the changes and the motivation behind them. Explain the context of the problem that your pull request solves or improves. If it fixes a bug or resolves an issue, please include that information here.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so others can reproduce. List any relevant details for your test configuration.
**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:
Please add any other information …

Implement Solution for "Permutation in String" Problem

---

solutions/day07/KrounositySolution.java

- Added .java solution file for October 7, 2024 leetcode daily solution
- Proper commenting for better comprehension

Add October 7, 2024 solution

---

solutions/day01/solution_python.py

This pull request implements the solution for the problem "Check Arithmetic Subarrays" from LeetCode. The task is to verify if each subarray in the provided ranges can be rearranged to form an arithmetic sequence.
Fixes #1 
This solution has been tested using various test cases provided by LeetCode, as well as additional custom cases to ensure the logic is sound.
**Test Configuration**:
* Firmware version: N/A
* Hardware: N/A
* Toolchain: Python
* SDK: N/A
This solution is efficient, sorting each subarray and then checking the arithmetic condition in O(k log k) time for each query, where k is the length of the subarray. This approach ensures that the time complexity is manageable within the problem's constraints.

feat(add): solution python

---

solutions/day02/solution_python.py

Issue: #2 
- Language used: Python
- Time Complexity: O(n*logn)
- It uses a set to collect unique elements.
- It assigns ranks based on the sorted unique elements.
- It replaces the original array values with their corresponding ranks.

Added day2 solution in python

---

solutions/day07/Readme.md
solutions/day07/solution_python.py

- Adds solution for LeetCode Daily Challenge on (Monday 07/10/2024) in (Python).
- This problem involves reducing a string by repeatedly removing the substrings "AB" or "CD" whenever they appear. The goal is to find the minimum possible length of the string after all such removals.
Used a stack to simulate the removals
Fixes issue: # 7
- **Language Used**: Python

Added the Python solution of Leetcode-daily Challenge and readme file explaining the code

---

solutions/day03/solution_python.py

Issue: #3 
- Language used: Python
- Time Complexity: O(n)
- Calculate Total Sum: Find the sum of all elements and compute its remainder when divided by p.
- Check Divisibility: If the remainder is 0, return 0 (no need to remove any subarray).
- Prefix Mod Dictionary: Track prefix sums modulo p using a dictionary to find subarrays that can make the total sum divisible by p.
- Iterate Through Array: For each element, update the prefix sum and check if a valid subarray exists using the dictionary.
- Update Minimum Length: If a valid subarray is found, update the minimum length.
- Return Result: Return the length of the smallest valid subarray, or -1 if no such subarray exists.

added solution for day3 in python

---

solutions/day07/solutionInConstantSpace.cpp

This pull request introduces an optimized solution for the problem of reducing a string's length by removing occurrences of the substrings "AB" and "CD". The implementation utilizes a constant space approach, efficiently minimizing the string length without relying on additional data structures.

Optimize Minimum String Length Reduction Using Constant Space

---

solutions/day04/solution_python.py

Issue: #4 
- Language used: Python
- Time Complexity: O(n*logn)
- Sorting: The array is sorted first.
- Two Pointers: i starts from the beginning and j from the end of the array, pairing elements.
- Check Consistent Pair Sum: Ensure the sum of paired elements remains constant. If not, return -1.
- Accumulate Products: Multiply each pair and accumulate the result in ans.
- Return: Return the total accumulated product.

Added solution for day4 in python

---

solutions/day08/solution.cpp

This pull request introduces a solution to the problem of determining the minimum number of swaps required to balance a string of brackets. The solution efficiently counts unmatched opening and closing brackets and calculates the required swaps based on these counts.

Implemented Minimum Swaps to Balance Bracket String

---

solutions/day08/README
solutions/day08/solution.go

- Adds solution for LeetCode Daily Challenge on Tuesday the 8th in (Programming Language).
Fixes issue: #9 
- [✔ ] I have placed my solution in the correct folder (`solutions/dayXX/`).
- [ ✔] My code follows clean coding practices and is efficient.
- [ ✔] I have added comments in my code to explain the approach.
- [ ✔] I have updated the `README.md` for the specific day with a brief explanation of my solution.
- [ ✔] I have tested the solution on LeetCode and it works correctly.
- **Language Used**: Go (Golang)
- **Space Complexity**: O(1)

Valid Palindrom solution in Go

---

solutions/day12/solution_cpp.cpp

- Adds solution for LeetCode Daily Challenge on October 12, 2023, in C++.
- The approach involves storing start and end events for intervals, sorting them, and counting active intervals to find the maximum overlap, which determines the minimum number of groups required.
- **Language Used**: C++
- **Time Complexity**: O(n log n)
For each interval, we store two events: one for when the interval starts and one for when it ends. We sort these events and process them in order. If two events happen at the same time, the ending of an interval is processed before the start of a new interval. We traverse through the sorted events, keeping track of the current …

Add Day 12 solution in c++

---

solutions/day12/solution_java.java

- Adds solution for LeetCode Daily Challenge for 12th October 2024 in Java.
- Used priority queue to track available chairs for all persons with time intervals
Fixes issue: #12 
- **Time Complexity**: O(n log n)
N/A

Added solution_java.java for day 12

---

solutions/day13/solution_java.java

- Adds solution for LeetCode Daily Challenge for 12th October 2024 in Java.
- Used priority queue to track available chairs for all persons with time intervals
Fixes issue: #13 
- **Time Complexity**: O(n log n)
N/A

Added day13 solution in java

---

.idea/.gitignore
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
leetcode-daily-october-hacktoberfest-2024.iml
solutions/day13/uniqueEmailAddress/Readme.md
solutions/day13/uniqueEmailAddress/Solution.java
solutions/solutions.iml

unique-email-address

---

solutions/day12/Readme.md
solutions/day12/solution_python.py

- Adds a solution for the LeetCode Daily Challenge for October 12th, 2024, implemented in Python.
- The solution uses a two-pointer technique to manage available chairs for persons based on their time intervals.
Fixes issue: #12 
- **Language Used**: Python
- **Time Complexity**: O(n log n)
Alternative approach
1. Sort the intervals by their start times to analyze when overlaps happen.
2. Track how many intervals overlap at any point:
- Use the idea of "event points": Mark when each interval starts and ends.
- Increase the count when an interval starts and decrease it when it ends.
3. Determine the maximum overlap at any point: The maximum number of overlapping intervals at the same time tells you the …

Add Day 12 solution in Python

---

solutions/day03/solution_elisp.el

- Adds solution for LeetCode Daily Challenge on 2024-10-03 in elisp.
- **Language Used**: elisp

Added elisp solution to day 3

---

solutions/day14/Readme.md
solutions/day14/solution_cpp.cpp

- Adds the solution for LeetCode Daily Challenge on Monday and 14th October in C++.
- Briefly explain the approach taken to solve the problem:
- Utilized a max-heap (priority queue) to efficiently extract and update the largest element k times.
- Repeatedly replaced the maximum element with its one-third value (rounded up) while adding the max to the sum.
Fixes issue: #14 
- **Language Used**:  C++
- **Time Complexity**: O(n log n + k log n)
- **Space Complexity**:  O(n)

Add Day 14 solution in C++

---

solutions/day01/solution_cpp.cpp

Solution of day 1 question on leetcode in cpp

---

solutions/day15/solution_java.java

- Adds solution for LeetCode Daily Challenge for 12th October 2024 in Java.
- Used priority queue to track available chairs for all persons with time intervals
Fixes issue: #15 
- **Space Complexity**: O(1)
N/A

Added solution_java.java for day15

---

solutions/day15/Solution_cpp.cpp

Day 15 solution in cpp

---

solutions/day15/Separate Black and White Balls.java

Added Separate Black and White Balls Problem Solution With a new Approach in Java Programming Language.

Create Separate Black and White Balls.java

---

solutions/day16/Solution_cpp.cpp

Added: Day 16 CPP Solution for LongestDiverseString

---

solutions/day17/Readme.md
solutions/day17/day17.java

- Adds solution for LeetCode Daily Challenge on Thursday, 17th October in Java.
Fixes issue: #17
- **Time Complexity**: O(n^2)
Beginner friendly approach

Solution for Day 17

---

solutions/day17/Day17.py

- Adds solution for LeetCode Daily Challenge on Thursday ,17 October in Python.
- **Language Used**: Python

Solved Day17 problem in python

---

solutions/day18/solution_java.java

I have added solution to the leetcode problem on Day 18 which is problem number 2044. Count Number of Maximum Bitwise-OR Subsets in Java language.  I have applied recursion to generate count of max. bitwise or subsets and my intuition was basic take and not-take approach.

Added Day 18 solution in Java

---

solutions/day18/solution_cpp.cpp
solutions/day19/solution_cpp.cpp

🚀 What does this PR do?
Adds a solution for the LeetCode Daily Challenge on (Day and Date) in C++.
The solution implements a recursive approach to solve the problem "Find Kth Bit in Nth Binary String".
📝 Issue Reference:
🔍 Checklist:
I have placed my solution in the correct folder (solutions/dayXX/).
My code follows clean coding practices and is efficient.
I have added comments in my code to explain the approach.
I have updated the README.md for the specific day with a brief explanation of my solution.
I have tested the solution on LeetCode and it works correctly.
🔧 Solution Details:
Language Used: C++
Time Complexity: O(n), where n is the depth of recursion. At each recursive …

Add Day 19 solution in C++

---

solutions/day16/solution_java.java

🚀 What does this PR do?
Adds a solution for the LeetCode Daily Challenge on (Day and Date) in Java.
The solution implements a greedy approach to solve the problem "Longest Happy String", using a priority queue to manage character frequencies.
📝 Issue Reference:
🔍 Checklist:
I have placed my solution in the correct folder (solutions/dayXX/).
My code follows clean coding practices and is efficient.
I have added comments in my code to explain the approach.
I have updated the README.md for the specific day with a brief explanation of my solution.
I have tested the solution on LeetCode and it works correctly.
🔧 Solution Details:
Language Used: Java
Time Complexity: O(a + b + c) where …

day 16 solution in java

---

solutions/day19/README.md
solutions/day19/solutions/day19/solution_java.java

- The solution implements a recursive approach to solve the problem "Find kth Bit".
Fixes issue: #19 
- I have placed my solution in the correct folder (`solutions/dayXX/`).
- My code follows clean coding practices and is efficient.
- I have added comments in my code to explain the approach.
- I have updated the `README.md` for the specific day with a brief explanation of my solution.
- I have tested the solution on LeetCode and it works correctly.
- **Time Complexity**:  O(n)
- **Space Complexity**:  O(n)

Add solution for Day 19 problem in Java

---

solutions/day20/README.md
solutions/day20/Solution.java

- Adds solution for LeetCode Daily Challenge on 20th October 2024,Sunday in Java.
- The approach uses a stack to process boolean expressions. As we traverse the expression, we skip commas and parentheses, pushing booleans (`t`, `f`) and operators (`&`, `|`, `!`) onto the stack. When encountering a closing parenthesis, we evaluate the subexpression by popping values, tracking whether we find `t` or `f`. Based on the operator, we push the result back onto the stack: for `!`, we push the opposite; for `&`, we push `f` if any `f` is found, otherwise `t`; for `|`, we push `t` if any `t` is found, otherwise `f`. The final result will be the top value in the stack.
- [ ☑️ ] I have …

Added 20th October Code

---

solutions/day21/solution.cpp
solutions/day21/solution.js

cpp and js solution to Daily challenge leetcode Day 21 added successfully . please take a time to review it.

issue #21 solved 

---

solutions/day23/solution_cpp.cpp
solutions/day23/solution_java.java
solutions/day23/solution_python.py

Day 23 : Cousins in Binary Tree II

---

solutions/day10/solution_java.java

- Adds solution for LeetCode Daily Challenge on (Day 10) in (Java).
Fixes issue: #10 

Adding Java Solution for Day 10

---

solutions/day25/solution.java

This code is of Daily LeetCode challenge of 24 October 2024 in java language.
- Sort the folders: Sorting ensures that sub-folders will come immediately after their parent folder.
- Traverse the sorted list: While traversing, we compare each folder with the previously added folder to determine whether it is a sub-folder or not. If it is not a sub-folder, we add it to the result list.
- day25 solution of 25 October 2024
- Problem-1233. Remove Sub-Folders from the Filesystem
- I have placed my solution in the correct folder (`solutions/day25/`).
- My code follows clean coding practices and is efficient.
- I have added comments in my code to explain the approach.
- I have updated the `README.md` for the specific day with a brief explanation of my solution.
- I have tested the solution on …

Added solution of leetcode challenge 25Oct 2024

---

solutions/day26/solution_java.java

- Adds solution for LeetCode Daily Challenge of 26 October in Java.
- Initial Setup: Two arrays left[] and right[] are initialized to store maximum depths for left-to-right and right-to-left traversals, respectively.
-First Traversal (Left): A depth-first traversal fills the left[] array with maximum depth values encountered while traversing down the left branches of the tree.
-Second Traversal (Right): A second depth-first traversal fills the right[] array with maximum depth values while traversing down the right branches of the tree.
-Query Processing: For each query, the result is the maximum value from the left[] and right[] arrays at the queried node's position.
day26 of October daily challenge [2458. Height of Binary Tree After Subtree Removal Queries]
- I have placed my solution in …

Added leetCode daily challenge of 26 Oct

---

solutions/day27/README.md
solutions/day27/solution_java.java

- Adds solution for LeetCode Daily Challenge on Day 27 in Java.
- This solution uses dynamic programming to count square submatrices of 1s. For each cell in the matrix, if it's 1, we check its top, left, and top-left neighbors to see how big of a square we can form there, then add that to our total count.
Fixes issue: #27 
- **Time Complexity**: O(*m* * *n*)
- **Space Complexity**: O(*m* * *n*)

solution for day 27 with java #27
